name: emprende_app
description: Una aplicación para gestionar tu emprendimiento.

# Previene la publicación accidental en pub.dev.
publish_to: 'none'

# La siguiente línea define la versión y el número de compilación de tu aplicación.
# La versión es un número de tres partes seguido de un número de compilación opcional.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Las dependencias son los paquetes externos que tu aplicación necesita para funcionar.
dependencies:
  flutter:
    sdk: flutter

  # --- DEPENDENCIAS PRINCIPALES DE LA APP ---

  # Paquete estándar para iconos de estilo iOS.
  cupertino_icons: ^1.0.2

  # Para la base de datos local SQL.
  sqflite: ^2.3.0

  # Helper para construir rutas de archivos, usado con sqflite.
  path: ^1.8.3

  # Para seleccionar imágenes de la galería o cámara del dispositivo.
  image_picker: ^1.0.4

  # Para formatear fechas, números y otros datos de forma internacionalizada.
  intl: ^0.18.1
  
  # Backend de sqflite necesario para que la base de datos funcione en 
  # plataformas de escritorio (Windows, Linux, macOS).
  sqflite_common_ffi: ^2.3.0+4


# Las dev_dependencies son paquetes que solo se necesitan durante el desarrollo,
# como herramientas de testing o linters (análisis de código).
dev_dependencies:
  flutter_test:
    sdk: flutter

  # El conjunto recomendado de "linters" (reglas de análisis de código) para aplicaciones Flutter.
  flutter_lints: ^2.0.0

# La siguiente sección es específica de Flutter.
flutter:

  # La siguiente línea asegura que la fuente Material Icons esté incluida en tu aplicación.
  uses-material-design: true

  # Para añadir assets (como imágenes) a tu aplicación, descomenta esta sección.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para añadir fuentes personalizadas a tu aplicación, descomenta esta sección.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700